groups:
- name: managing-ocp-cluster-rules
  interval: 30s # defaults to global interval
  rules:
    - alert: Minimum Number of Application Nodes
      expr: sum(up{node_role_kubernetes_io_compute="true",job="kubernetes-nodes"}) < 0
      for: 2m
      labels:
        severity: critical
        type: ansible-tower
      annotations:
        description: The Number of Application Nodes is Below Minimum Threshold
        summary: Minimum Application Nodes
